name: core
description: A new Flutter package project.

publish_to: 'none' 
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^4.2.0
  dio: ^4.0.1
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  flutter_svg: ^0.23.0+1
  dartz: ^0.10.0
  flutter_secure_storage: ^4.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.4

flutter: